# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d6f9784254385f1a6ac09d8b41cec44b"
name = "Product bulk editor"
application_url = "https://product-bulk-editor.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "bulk_operations/finish" ]
  uri = "/webhook/bulk-finish"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://product-bulk-editor/auth/callback",
  "https://product-bulk-editor/auth/shopify/callback",
  "https://product-bulk-editor/api/auth/callback"
 ]
